hashicorp/packer-plugin-vsphere

builder/vsphere/driver/vm.go

Correcting VMWare resource reference value lookup order for ResourcePool and VMHomeStorage since they are dependent on the original input values for Cluster and Host
packer-plugin-vsphere:v0.0.1 - Execution Error Messae:
```
==> dnsmasq.vsphere-clone.vm-base: Importing VM template packer-dnsmasq:0.0.0-1b965293-alpine-3.12.6 to Content Library...
==> dnsmasq.vsphere-clone.vm-base: Failed to import template packer-dnsmasq:0.0.0-1b965293-alpine-3.12.6: resource pool 'domain-c346/Resources/HashiCorpPackerVMs' not found
==> dnsmasq.vsphere-clone.vm-base: Provisioning step had errors: Running the cleanup provisioner, if present...
```

Correcting VMWare Resource ID/Value Loading Order for Importing VM-Template to Content Library

---

builder/vsphere/common/step_import_to_content_library.go
builder/vsphere/common/step_template.go

Setting Secure boot with UEFI firmware works when the VM is created, but is lost when the VM is pushed to a content library. This appears to be becuase the boot order section is not removed before the template is pushed to the content library. It is removed as part of the VM cleanup code, but that is tied to the VM create/Remove code rather tightly.
I have copied the boot order clearing code into the template step before the push happens. This works locally and a VM created from the template item now has UEFI and Secure Boot.
Closes #13

Fix firmware reverting to BIOSwhen pushing to template in content library.

---

builder/vsphere/clone/step_clone.go
builder/vsphere/driver/driver.go
builder/vsphere/driver/driver_mock.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_mock.go
builder/vsphere/iso/step_create.go

This PR resolves the issue where `packer` is not able to remove a `vsphere` template if it has snapshots `create_snapshot = true` in both the `vsphere-clone` and `vsphere-iso` builders.  This fix will convert a template back to a virtual machine so that the VMware API will allow it to be deleted.
The same tests that were in the [original packer issue #10889](https://github.com/hashicorp/packer/issues/10889) were run to verify that it is working properly.
```text
$ ~/bin/packer build  .
vsphere-clone.cleanuptest: output will be in this color.
Build 'vsphere-clone.cleanuptest' errored after 6 seconds 33 milliseconds: Templates/QA/forcecleanuptest already exists, you can use -force flag to destroy it: <nil>
==> Wait completed after 6 seconds 43 milliseconds
==> Some builds didn't complete …
```

Fix removing templates with snapshots

---

builder/vsphere/driver/vm.go

This fixes the case when we want to target a specific host within a cluster as given in the documentation:
```json
"cluster": "cluster1",
"host": "esxi-2.vsphere65.test",
```
The **spec.location.host** SOAP parameter was not set in that case.
This has been tested on a real vCenter and it works fine. 
I created a test for this, but unfortunately the govmomi vCenter Simulator is buggy on that matter and just ignores this parameter, so I did not include it in this PR. 
I did write a patch for the govmomi simulator and will shortly submit a pull request.

Take the host configuration into account while cloning a VM

---

builder/vsphere/clone/builder.go
builder/vsphere/clone/config.go
builder/vsphere/clone/config.hcl2spec.go
builder/vsphere/common/step_snapshot.go
builder/vsphere/iso/builder.go
builder/vsphere/iso/config.go
builder/vsphere/iso/config.hcl2spec.go
docs-partials/builder/vsphere/clone/Config-not-required.mdx
docs-partials/builder/vsphere/iso/Config-not-required.mdx

Adds a snapshot_name option to allow specifying the name of the snapshot created by create_snapshot in both vsphere-clone and vsphere-iso builders.
Closes #65

Added snapshot_name option for vsphere-clone and vsphere-iso builders

---

builder/vsphere/clone/builder.go
builder/vsphere/iso/builder.go

In the documentation there was a cd_content setting but this wasn't working, because it seems to be forgotten in the StepCreateCD step config of the iso and clone builder.

Pass cd_content config in vsphere iso and clone builder

---

builder/vsphere/common/storage_config.go
docs-partials/builder/vsphere/common/StorageConfig-not-required.mdx

The documentation does not include the valid `disk_controller_type` of lsilogic-sas. There was an issue/pr mentioned in the jetbrains repo (https://github.com/jetbrains-infra/packer-builder-vsphere/issues/188) that led me to this conclusion.

Modify Documentation to Add lsilogic-sas As Storage Controller Option

---

docs/builders/index.mdx

This PR fixes the URL for vsphere-clone.
Without this commit, it would result in the nonexisting URL:
https://www.packer.io/docs/builders/docs/builders/vsphere/vsphere-clone
With this fix, it results in the existing URL:
https://www.packer.io/docs/builders/vsphere/vsphere-clone

Fixed URL to vsphere-clone

---

builder/vsphere/clone/builder.go
builder/vsphere/common/step_export.go
builder/vsphere/common/step_export.hcl2spec.go
builder/vsphere/iso/builder.go
docs-partials/builder/vsphere/common/ExportConfig-not-required.mdx

- Update documentation for export.images argument
- Add image_files configuration argument
The existing argument for including image files is called `images`,
which is a bit misleading. This commit adds a new argument
`image_files` and deprecates the old one.
Closes #95

export options update

---

docs/builders/vsphere-clone.mdx

- Updates "VMWare Vsphere" to the proper "VMware vSphere" naming.
- Updates instances of "Vsphere" to the proper "vSphere" naming.
- Updates "Required vSphere Permissions" to the proper "Required vSphere Privileges" terminology.

Correct product name and terms

---

docs/builders/vsphere-clone.mdx
docs/builders/vsphere-iso.mdx

Some links were still pointing to the old default branch "master". They have been updated to "main".

Updated branch from master to main

---

docs/post-processors/vsphere.mdx
post-processor/vsphere/post-processor.go
post-processor/vsphere/post-processor.hcl2spec.go

The change that I am making involves adding an additional configuration option to the vsphere post processor which would allow the user to specify the virtual hardware version of the virtual machine that will be deployed.  Nothing particularly complicated, as ovftool includes an argument which allows for this. and I simply take advantage of the aforementioned argument.  I also modified the help content to incorporate this new configuration option.  I had to modify the plugin because of a need for my particular project, and I figured that I would make the modification part of the official plugin.

Hardware version post processor option

---

builder/vsphere/common/step_import_to_content_library.go
builder/vsphere/common/step_import_to_content_library.hcl2spec.go
docs-partials/builder/vsphere/common/ContentLibraryDestinationConfig-not-required.mdx

Support for specifying the `Flags` parameter of the OVF CreateSpec.
Closes #186 
I suggest a syntax that mirrors how the OVF CreateSpec API is defined:
- https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/api/vcenter/ovf/library-item/post/
- https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/data-structures/Ovf/LibraryItem/CreateSpec/
```hcl
content_library_destination {
name = template_name
library = content_library
ovf = true
ovf_flags = [ "EXTRA_CONFIG" ]
}
```

Add support for specifying flags when importing an OVF template into a content library

---

builder/vsphere/clone/config.hcl2spec.go
builder/vsphere/common/step_hardware.go
builder/vsphere/common/step_hardware.hcl2spec.go
builder/vsphere/driver/vm.go
builder/vsphere/iso/config.hcl2spec.go
docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx

Adds add support for number of `displays` in the `vsphere` builders.
The number of supported displays for vSphere 7.0 `== 10`.
- If `displays` is omitted, the default number `= 1`.
- If `displays` is set to `0`, it is an invalid value and will set the default (`1`)
- If `displays` is set to `>10` (e.g., `11`), the API configuration the API will report an invalid configuration. This is dictated by the virtual hardware version. 
Adds support for configuring the number of displays by @tenthirtyam in https://github.com/hashicorp/packer-plugin-vsphere/pull/201.
Closes #80
**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

feat: add support for number of `displays` in the `vsphere` builders

---

builder/vsphere/common/step_import_to_content_library.go
builder/vsphere/driver/driver.go
builder/vsphere/driver/driver_mock.go
builder/vsphere/driver/library.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_test.go
docs-partials/builder/vsphere/common/ContentLibraryDestinationConfig-not-required.mdx
go.mod
go.sum

Closes #175
Enable setting the description field of an OVF template
published into a content library.
Requires updating govmomi to 0.27 where the UpdateLibraryItem
is supported.

Add description of OVF content library item

---

docs/post-processors/vsphere-template.mdx
docs/post-processors/vsphere.mdx

- Adds HCL examples for the `vsphere-template` post-processor.
- Minor edits and formatting of the documentation.
Closes: #205

docs: Add HCL examples for the `vsphere-template` post-processor

---

builder/vsphere/driver/vm.go
builder/vsphere/iso/step_create.go
docs-partials/builder/vsphere/iso/CreateConfig-not-required.mdx
docs-partials/builder/vsphere/iso/NIC.mdx

Removes the check that prevents the creation of a VM without a network adapter, thus allowing to create a VM without network adapters 
Closes #202

enhancement: make assignment of network_adapters optional

---

builder/vsphere/common/artifact_test.go
builder/vsphere/driver/vm_clone_acc_test.go
builder/vsphere/driver/vm_create_acc_test.go
post-processor/vsphere/post-processor_test.go

* Add nolint:unused for defined functions that are used as functional arguments.
* Remove unneeded calls to Sprintf(...)

Fix lint checker errors

---

docs/builders/vsphere-clone.mdx
docs/builders/vsphere-iso.mdx
docs/builders/vsphere-supervisor.mdx

Updates the documentation for each builder to note that support follows the the VMware Product Lifecycle Matrix from General Availability to End of General Support.
> _The builder supports versions following the VMware Product Lifecycle Matrix from General Availability to End of General Support. Builds on versions that are end of support may work, but configuration options may throw errors if they do not exist in the vSphere API for those versions._
GH-238

docs: update support references

---

builder/vsphere/driver/vm.go
go.mod
go.sum

Updates the requirements on `vmware/govmomi` to permit the latest version.
<details>
<summary>Release notes sourced from <a href="https://github.com/vmware/govmomi/releases">vmware/govmomi </a>releases</summary>
<blockquote>
> Release Date: 2022-07-06
- [d6dd8fb3]	Typos in vim25/soap/client CA tests
- [e086dfe4]	generate negative device key in AssignController
- [371a24a4]	Interface conversion panic in pkg simulator
- [a982c033]	use correct controlflag for vslm SetControlFlags API test
- [37b3b24c]	avoid possible panic in govc metric commands
- [310516e2]	govc: disambiguate vm/host search flags in vm.migrate
- [6af2cdc3]	govc-tests in Go v1.18
- [142cdca4]	Security update golangci-lint
- [971079ba]	use correct vcenter.DeploymentSpec.VmConfigSpec json tag
- [e6b5974a]	Add versioned …

chore(deps): bump vmware/govmomi from v0.26.1 to v0.29.0

---

builder/vsphere/clone/config.hcl2spec.go
builder/vsphere/clone/step_clone.go
builder/vsphere/clone/step_clone.hcl2spec.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx

Added a support for destroying VM after vsphere-clone builder is completed successfully.
Using `destroy: true` flag under the plugin configuration.
Example:
```
source "vsphere-clone" "my_clone" {
communicator         = "something"
insecure_connection  = "something"
password             = "something"
username             = "something"
ssh_private_key_file = "something"
ssh_username         = "something"
boot_wait            = "something"
ip_wait_timeout      = "something"
template             = "something"
vcenter_server       = "something"
datacenter           = "something"
cluster              = "something"
host                 = "something"
datastore            = "something"
vm_name              = "something"
folder               = "something"
destroy              = true
}
```
Tests: …

Allow destroy VM after vsphere-clone successful build (#168)

---

builder/vsphere/common/step_connect.go
builder/vsphere/driver/driver.go
builder/vsphere/driver/driver_mock.go
builder/vsphere/driver/vm.go

vSphere CLS API has a limit of 150 concurrents session users. Each session is released automatically after 1 hour.
The Driver is creating new sessions in every packer execution through `client.SessionManager.Login(ctx, credentials)` method, but not closing it.
The changes are mainly:
* Create a new method in Driver Interface to logout from vSphere soap and rest client.
* In the cleanup of `step_connect.go` retrieve the Driver from the state and do the Driver cleanup also.
* In vm.go, this PR adds `logout` when something fails. 
Closes #217

feat: improve session handling to mitigate session saturation

---

builder/vsphere/common/step_connect.go

The cleanup method executed at the end of the process calls always an API REST method to delete the active session through a driver's logout:
`DELETE https://${vSphere}/rest/com/vmware/cis/session`
If this the logout is called twice for a user_id session, it shows in the UI an error in the step_connect. 
The first time, the session is cleaned, but the second gives an `401 Unauthorized`, doing nothing. This call is innocuous.
In the cleanup method of step_connect, whenever there is an problem calling to the API REST it is showed to the user, giving a false positive error.
The aim of this PR is to dump the message to the log as a warning, and don't show in the UI.
Closes #286

fix: log level messages closing sessions

---

builder/vsphere/common/step_download_test.go
builder/vsphere/common/step_export.go
builder/vsphere/common/storage_config.go
builder/vsphere/driver/driver_test.go
builder/vsphere/iso/step_create.go
docs-partials/builder/vsphere/common/DiskConfig.mdx
docs-partials/builder/vsphere/common/ExportConfig.mdx
docs-partials/builder/vsphere/iso/NIC.mdx
go.mod

- github: remove test-plugin-example workflow
- go.mod: bump go version from 1.18 to 1.19

bump go 1.18 to 1.19

---

.web-docs/metadata.hcl

Since ISO and clone are generally more used, and for consistency compared to the components paragraph, we reorganise the metadata/ToC for the components of the plugin.

web-docs: place ISO before clone/supervisor

---

builder/vsphere/driver/vm.go

- Adding additional logging 
- Separate method for Logout
- Ran into a panic when attempting to create a vSphere template and import into a content library. Noticed there weren't any helpful logs to help troubleshoot.
- `panic: runtime error: invalid memory address or nil pointer dereference` ..... vm.go:945
- https://github.com/hashicorp/packer-plugin-vsphere/blob/91e51c0b744025ca8554df6779e12b7f6f8c25f9/builder/vsphere/driver/vm.go#L943-L947
Closes #316 
Closes #311

fix: log errors prior to logout

---

builder/vsphere/supervisor/step_watch_source.go
builder/vsphere/supervisor/utils_test.go

This PR updates the Supervisor test util function `checkOutputLines` to skip the current actual output if it contains "continue checking" line. This is to avoid failing the test in `step_watch_source.go` where the VM ingress IP may not be set immediately, causing `retry.Config` to output "continue checking" and retry.
Testing Done:
```console
$ go test -count=100 -run ^TestWatchSource_Run$ github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/supervisor 
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/supervisor   100.849s
```

Update Supervisor test to skip output from retry

---

builder/vsphere/supervisor/utils_test.go

This is a follow-up change to https://github.com/hashicorp/packer-plugin-vsphere/pull/321 which appears still failing the [CI test](https://github.com/hashicorp/packer-plugin-vsphere/actions/runs/6813905834/job/18529542723). 
To verify, I manually updated the test code to ensure the timing issue occurs:
```console
--- a/builder/vsphere/supervisor/step_watch_source_test.go
+++ b/builder/vsphere/supervisor/step_watch_source_test.go
@@ -116,6 +116,8 @@ func TestWatchSource_Run(t *testing.T) {
vmObj.Status.VmIp = testVMIP
_ = kubeClient.Update(ctx, vmObj, opt)
+       time.Sleep(time.Second)
+
vmServiceObj.Status.LoadBalancer.Ingress[0].IP = testIngressIP
_ = kubeClient.Update(ctx, vmServiceObj, opt)
```
Running the above test against upstream/main:
```console
$ go test -count=1 -run …
```

fix: update vsphere-supervisor test to skip output from retry (follow-up)

---

.github/dependabot.yml
builder/vsphere/driver/library.go
builder/vsphere/driver/vm.go
go.mod
go.sum

- Bumps `github.com/vmware/govmomi` from 0.29.0 to 0.33.1.
- Added `github.com/vmware/govmomi` to dependabot dependency checks.
- Address changes needed in `vm.go` and `library.go` for the content library items and tested.
> **Notes**
>
>`github.com/vmware/govmomi 0.33.1`
>
> <details>
> <summary>Release Notes</summary>
> <p><em>Sourced from <a href="https://github.com/vmware/govmomi/releases">github.com/vmware/govmomi's releases</a>.</em></p>
> <blockquote>
> <h2>v0.33.0</h2>
> <p></p>
> <h2><a href="https://github.com/vmware/govmomi/compare/v0.32.0...v0.33.0">Release v0.33.0</a></h2>
> <blockquote>
> <p>Release Date: 2023-10-25</p>
> </blockquote>
> <h3>💫 <code>govc</code> (CLI)</h3>
> <ul>
> <li>[5264e839]	add cluster.change '-ha-admission-control-enabled' flag</li>
> <li>[3bcaf429] …

chore(deps): bump `github.com/vmware/govmomi` from 0.29.0 to 0.33.1

---

.web-docs/components/builder/vsphere-clone/README.md
builder/vsphere/clone/step_clone.go
builder/vsphere/clone/step_clone_test.go
builder/vsphere/driver/vm_test.go
builder/vsphere/iso/step_create.go
builder/vsphere/iso/step_create_test.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx

- Sets the MAC address to lowercase.
- Update "Mac address" to "MAC address".
Ref: [VMware KB 82139](https://kb.vmware.com/s/article/82139)
Closes #324

fix: set mac address to lowercase

---

builder/vsphere/common/step_add_flag.go
builder/vsphere/common/step_add_flag_test.go
docs-partials/builder/vsphere/common/FlagConfig-not-required.mdx

- `vtpm` does **not** need to be set to `true` when `vbs_enabled` is set to `true`.
Closes #339

fix: remove vtpm req for vbs

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/common/step_add_cdrom.go
docs-partials/builder/vsphere/common/CDRomConfig-not-required.mdx

Updates the documentation for `iso_paths`.
Closes #313

docs: update `iso_paths`

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/builder.go
builder/vsphere/common/step_export.go
builder/vsphere/common/step_export.hcl2spec.go
builder/vsphere/iso/builder.go
docs-partials/builder/vsphere/common/ExportConfig-not-required.mdx
docs-partials/builder/vsphere/common/ExportConfig.mdx

- Removes deprecated `images` option that was noted to be removed over 2 years ago.
- Updated export configuration descriptions.
- Simplified `manifest` validation.
- Updated to use `ui.Say` versus `ui.Message` for output consistency.
- Added code comments.
- Improved output and error messaging for output consistency.
```bash
...
==> vsphere-iso.linux-photon: Executing shutdown command...
==> vsphere-iso.linux-photon: Deleting Floppy drives...
==> vsphere-iso.linux-photon: Eject CD-ROM drives...
==> vsphere-iso.linux-photon: Deleting CD-ROM drives...
==> vsphere-iso.linux-photon: Exporting to Open Virtualization Format (OVF)...
==> vsphere-iso.linux-photon: Downloading linux-photon-4.0-develop-disk-0.vmdk...
==> vsphere-iso.linux-photon: Exporting linux-photon-4.0-develop-disk-0.vmdk... …
```

chore: Remove support for deprecated `images` configuration attribute in favor of `image_files` attribute in the export config block

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/step_clone.go
builder/vsphere/common/storage_config.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
docs-partials/builder/vsphere/common/DiskConfig-not-required.mdx
docs-partials/builder/vsphere/common/DiskConfig-required.mdx

- Updates `disk_size` from MB to MiB.
- Minor text updates.
Closes #348 
```zsh
packer-plugin-vsphere on docs/mb-to-mib
➜ go fmt ./...         
packer-plugin-vsphere on docs/mb-to-mib
➜ make build
packer-plugin-vsphere on docs/mb-to-mib
➜ export PATH=$PATH:$(go env GOPATH)/bin
packer-plugin-vsphere on docs/mb-to-mib
2023/12/19 15:34:42 Copying "docs" to ".docs/"
2023/12/19 15:34:42 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on docs/mb-to-mib took 34.4s 
➜ make test
? …
```

docs: update `disk_size` from mb to mib

---

post-processor/vsphere-template/post-processor.go

Apparently this check is obsolete (see https://github.com/hashicorp/packer/issues/6975, specifically "You're right, the folder bound to the root doesn't do any effect at code level, that was because the[ first implementation ](https://github.com/bennu/packer/blob/2ddc07d3b9a84f59e65a6cc0fafd68db158645f5/post-processor/vsphere-template/step_create_folder.go#L43)used to use that, sadly I forgot to remove it when I changed it.") and still has an open issue (https://github.com/hashicorp/packer-plugin-vsphere/issues/3).  With this check in place, any attempt to use the vsphere-template post-processor seems to fail with errors like:
```
Error: Failed preparing post-processor-block "vsphere-template" ""
on ubuntu-2204.pkr.hcl line 303:
(source code not available)
1 error(s) occurred:
* Folder …
```

fix: remove obsolete path check

---

builder/vsphere/common/step_add_cdrom_test.go
builder/vsphere/common/step_reattach_cdrom_test.go
builder/vsphere/driver/vm_mock.go

There is an AddCdromCalledTimes which serves the same purpose

chore(tests): remove unnecessary `AddCdromCalled`

---

builder/vsphere/clone/step_customize.go
builder/vsphere/common/step_ssh_key_pair.go
builder/vsphere/driver/datastore_acc_test.go
builder/vsphere/iso/builder_acc_test.go
builder/vsphere/iso/step_create_test.go
builder/vsphere/supervisor/step_create_source.go
builder/vsphere/supervisor/step_create_source_test.go

`io/ioutil` is deprecated as of Go 1.16:
- Updates `ioutil.Discard` to `io.Discard`.
- Updates `ioutil.TempFile` to `os.CreateTemp`.
- Updates `ioutil.ReadFile` to `os.ReadFile`.
- Updates `ioutil.WriteFile` to `os.WriteFile`.
```console
packer-plugin-vsphere on  chore/ioutil-depreciation [!] via 🐹 v1.21.6 took 29.6s 
✦ ➜ make build
packer-plugin-vsphere on  chore/ioutil-depreciation [!] via 🐹 v1.21.6 took 8.7s 
✦ ➜ make test
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/version      [no test files]
ok …
```

chore: address `io/ioutil` depreciation

---

builder/vsphere/common/step_add_cdrom.go
builder/vsphere/common/step_add_cdrom_test.go
builder/vsphere/common/step_reattach_cdrom.go
builder/vsphere/common/step_reattach_cdrom_test.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_cdrom.go
builder/vsphere/driver/vm_mock.go

In PR #344 a feature to reuse an existing VM is being added. As part of that feature I had to factor out from `AddCdrom` the logic of creating a CD-rom as opposed to just mounting an image. Recently merged feature `reattach_cdroms` turned out to be a new user of the older logic, which made rebasing #344 non-trivial.
In this PR I refactor the `reattach_cdroms` logic to avoid unnecessarily calling `EjectCdroms`, `RemoveCdroms` and `AddCdrom` by calculating amount of CDroms that we want to have added/removed, and only calling the mentioned functions for that amount *(see the last commit)*.
This is a useful change in itself, disregarding whether #344 exists, so I'm sending it separately from the other PR. And it should simplify rebasing #344 later.

refactor: only add / remove minimul number of cdroms

---

.web-docs/components/builder/vsphere-clone/README.md
builder/vsphere/clone/config.go
builder/vsphere/clone/step_customize.go
builder/vsphere/clone/step_customize.hcl2spec.go
builder/vsphere/clone/step_customize_test.go
docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx

Closes #357 
Allows users to submit a custom Windows Sysprep file as text instead of as a file. #357 discusses why this PR is useful. windows_sysprep_file will be marked as deprecated in favor of windows_sysprep_text. 
Note: I have tested this on my own Packer builds and it works fine. I noticed that there are not any tests around customization, but I am happy to write some if necessary.

feat: add `windows_sysprep_text` field

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/config.hcl2spec.go
builder/vsphere/common/step_hardware.go
builder/vsphere/common/step_hardware.hcl2spec.go
builder/vsphere/common/step_hardware_test.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_test.go
builder/vsphere/iso/config.hcl2spec.go
docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx

These changes allow you to define a VirtualPrecisionClock device.
Closes #354
From @tenthirtyam 
```console
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 
➜ go get
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 took 3.0s 
➜ go mod tidy
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 
➜ go fmt builder/vsphere/driver/vm.go 
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 
➜ go fmt builder/vsphere/driver/vm_test.go 
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 
➜ go fmt builder/vsphere/common/step_hardware.go 
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 
➜ go fmt builder/vsphere/common/step_hardware_test.go 
packer-plugin-vsphere on  pr/367 [⇕$!] via 🐹 v1.22.0 
2024/02/26 14:26:48 Copying "docs" to ".docs/"
2024/02/26 14:26:48 …
```

feat: add support for precision clock device

---

CHANGELOG.md
README.md
builder/vsphere/clone/config_test.go
builder/vsphere/clone/step_clone_test.go
builder/vsphere/clone/step_customize.go
builder/vsphere/clone/step_customize_test.go
builder/vsphere/common/hcp_metadata.go
builder/vsphere/common/step_wait_for_ip.go
builder/vsphere/driver/disk_test.go
builder/vsphere/driver/library.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_clone_acc_test.go
builder/vsphere/iso/builder_acc_test.go
builder/vsphere/iso/step_create_test.go
post-processor/vsphere/artifact_test.go
post-processor/vsphere/post-processor_test.go

Technical Debt:
- Correct misspellings and grammar.
- Correct version of Go in `README.md` to match `go.mod`.
- Correct markdownlint issues in `CHANGELOG.md`.
```sh
> make generate
2024/03/01 22:55:03 Copying "docs" to ".docs/"
2024/03/01 22:55:03 Replacing @include '...' calls in .docs/
> make build   
> make test 
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/version      [no test files]
ok …
```

chore: correct typos and markdown

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/step_customize.go
builder/vsphere/common/step_hardware.go
builder/vsphere/common/storage_config.go
docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx
docs-partials/builder/vsphere/clone/CustomizeConfig.mdx
docs-partials/builder/vsphere/clone/GlobalDnsSettings-not-required.mdx
docs-partials/builder/vsphere/clone/GlobalDnsSettings.mdx
docs-partials/builder/vsphere/clone/GlobalRoutingSettings-not-required.mdx
docs-partials/builder/vsphere/clone/GlobalRoutingSettings.mdx
docs-partials/builder/vsphere/clone/LinuxOptions-not-required.mdx
docs-partials/builder/vsphere/clone/NetworkInterface-not-required.mdx
docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
docs-partials/builder/vsphere/common/StorageConfig-not-required.mdx

- Updates documentation for `vsphere-clone` customization.
- Updates all VMware vSphere references to vSphere 8.0.
```console
packer-plugin-vsphere on  docs/step-customize [!+] via 🐹 v1.22.0 took 11.7s 
➜ go fmt builder/vsphere/clone/step_customize.go
packer-plugin-vsphere on  docs/step-customize [!+] via 🐹 v1.22.0 
➜ go fmt builder/vsphere/clone/step_customize_test.go 
packer-plugin-vsphere on  docs/step-customize [!+] via 🐹 v1.22.0 
➜ go fmt builder/vsphere/common/step_hardware.go
packer-plugin-vsphere on  docs/step-customize [!+] via 🐹 v1.22.0 
2024/03/03 22:51:15 Copying "docs" to ".docs/"
2024/03/03 22:51:15 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on  docs/step-customize [!+] via 🐹 …
```

docs: `vsphere-clone` customize

---

.web-docs/components/builder/vsphere-clone/README.md
builder/vsphere/clone/step_clone.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
docs-partials/builder/vsphere/clone/vAppConfig-not-required.mdx

Updates descriptions for generated documentation.
```console
packer-plugin-vsphere on  docs/update-step-clone via 🐹 v1.22.0 
➜ make build   
packer-plugin-vsphere on  docs/update-step-clone via 🐹 v1.22.0 took 4.2s 
2024/03/04 22:16:49 Copying "docs" to ".docs/"
2024/03/04 22:16:49 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on  docs/update-step-clone via 🐹 v1.22.0 took 11.5s 
➜ make test    
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver      [no test files]
? …
```

docs: update `vsphere/clone/step_clone`

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/config.go
builder/vsphere/iso/config.go
docs-partials/builder/vsphere/clone/Config-not-required.mdx
docs-partials/builder/vsphere/iso/Config-not-required.mdx

Updates config documentation for `vsphere-clone` and `vsphere-iso`.
Testing
```console
packer-plugin-vsphere on  docs/update-clone-iso-config via 🐹 v1.22.0 
➜ make build
packer-plugin-vsphere on  docs/update-clone-iso-config via 🐹 v1.22.0 took 3.4s 
2024/03/04 21:59:25 Copying "docs" to ".docs/"
2024/03/04 21:59:25 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on  docs/update-clone-iso-config via 🐹 v1.22.0 took 11.6s 
➜ make test
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver      [no …
```

docs: update clone/iso config

---

.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/iso/step_create.go
docs-partials/builder/vsphere/iso/CreateConfig-not-required.mdx
docs-partials/builder/vsphere/iso/NIC-not-required.mdx
docs-partials/builder/vsphere/iso/NIC-required.mdx

- Updates descriptions for generated documentation.
- Provides the PowerShell syntax using `VMware.PowerCLI`. By using this method, you can get the list of supported guest os identifiers based on the version of ESXI in your environment.
```console
>make build
> make generate
2024/03/01 19:23:51 Copying "docs" to ".docs/"
2024/03/01 19:23:51 Replacing @include '...' calls in .docs/
```
`guest_os_type` (string) - Defines the guest operating system identifier for the virtual machine. If not specified, the setting defaults to `otherGuest`.
To get a list of supported guest operating system identifiers for your ESXi host run the following PowerShell command using `VMware.PowerCLI`:
```powershell
Connect-VIServer -Server …
```

docs: update `vsphere/iso/step_create`

---

builder/vsphere/examples/supervisor/jenkins-template.pkr.hcl

This PR adds the required steps in the supervisor builder Jenkins template file to get the `apt-get update` command working.
See https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ for more details.
Verified internally using the updated Jenkins template:
```console
==> vsphere-supervisor.vm: Creating temporary RSA SSH key for instance...
vsphere-supervisor.vm: Connecting to Supervisor cluster...
vsphere-supervisor.vm: Successfully connected to Supervisor cluster
...
==> vsphere-supervisor.vm: Provisioning with shell script: /var/folders/nf/cndlm4ts2bd9jz3dd667jfb80000gr/T/packer-shell350374452
vsphere-supervisor.vm: deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian binary/
vsphere-supervisor.vm: deb …
```

Update Jenkins template example for supervisor builder

---

.web-docs/components/post-processor/vsphere-template/README.md
docs-partials/post-processor/vsphere-template/Config-not-required.mdx
docs-partials/post-processor/vsphere-template/Config-required.mdx
docs-partials/post-processor/vsphere/Config-not-required.mdx
docs/post-processors/vsphere-template.mdx
post-processor/vsphere-template/post-processor.go
post-processor/vsphere-template/post-processor.hcl2spec.go
post-processor/vsphere-template/post-processor_test.go
post-processor/vsphere-template/step_choose_datacenter.go
post-processor/vsphere-template/step_create_folder.go
post-processor/vsphere-template/step_create_snapshot.go
post-processor/vsphere-template/step_mark_as_template.go

- Updates error messages to use a more well-formed structure.
- Updates and simplifies code comments.
- Updates post-processor to generate documentation from structs.
- Generates the updated post-processor documentation.
```console
packer-plugin-vsphere on  chore(post-processor)/update-vsphere-template [$!?] via 🐹 v1.22.1 
➜ make dev
packer-plugin-vsphere on  chore(post-processor)/update-vsphere-template [$!?] via 🐹 v1.22.1 
2024/03/14 14:01:06 Copying "docs" to ".docs/"
2024/03/14 14:01:06 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on  chore(post-processor)/update-vsphere-template [$!?] via 🐹 v1.22.1 took 11.6s 
➜ make build
packer-plugin-vsphere on  …
```

chore(post-processor): update `vsphere-template`

---

.web-docs/components/post-processor/vsphere/README.md
docs-partials/post-processor/vsphere/Config-not-required.mdx
docs-partials/post-processor/vsphere/Config-required.mdx
docs/post-processors/vsphere.mdx
post-processor/vsphere/post-processor.go
post-processor/vsphere/post-processor.hcl2spec.go

- Updates and simplifies code comments.
- Updates post-processor to generate documentation from structs.
- Generates the updated post-processor documentation.
```console
packer-plugin-vsphere on chore(post-processor)/update-vsphere
2024/03/18 11:09:48 Copying "docs" to ".docs/"
2024/03/18 11:09:48 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on chore(post-processor)/update-vsphere
➜ make dev  
packer-plugin-vsphere on chore(post-processor)/update-vsphere 
➜ make build
packer-plugin-vsphere on chore(post-processor)/update-vsphere
➜ make test
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/testing …
```

chore(post-processor): update `vsphere`

---

builder/vsphere/common/step_add_cdrom.go
builder/vsphere/common/step_add_cdrom_test.go

This fixes regression introduced by the commit
"common: deduplicate AddCdrom call by appending path to ISOPaths"
that was squashed into:
"refactor: only add / remove minimul number of cdroms (#355)"
It explained that the order is not guaranteed and does not matter, however the documentation says:
> If the "iso_url" is defined in addition to the "iso_paths", the
> "iso_url" is added to the VM first. This keeps the "iso_url" first
> in the boot order by default allowing the boot iso being defined by
> the iso_url and the vmware tools iso added from the datastore.
So fix the regression.
Fixes: https://github.com/hashicorp/packer-plugin-vsphere/issues/386

common: make sure to prepend remote iso path

---

go.mod
go.sum

Bump google.golang.org/protobuf from v1.31.0 to v1.33.0
Ref: https://github.com/hashicorp/packer-plugin-vsphere/security/dependabot/26
```console
packer-plugin-vsphere on  chore(post-processor)/update-vsphere [$!] via 🐹 v1.22.1 
➜ go get -u google.golang.org/protobuf           
go: upgraded google.golang.org/protobuf v1.31.0 => v1.33.0
packer-plugin-vsphere on  main [$!] via 🐹 v1.22.1 
➜ go mod tidy
packer-plugin-vsphere on  main [$!] via 🐹 v1.22.1 
➜ make build
packer-plugin-vsphere on  main [$!] via 🐹 v1.22.1 took 17.1s 
➜ make test
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/testi …
```

chore(deps): bump google.golang.org/protobuf from v1.31.0 to v1.33.0

---

.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/common/step_add_cdrom_test.go
builder/vsphere/common/step_reattach_cdrom.go
builder/vsphere/common/step_reattach_cdrom_test.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_cdrom.go
builder/vsphere/driver/vm_cdrom_test.go
builder/vsphere/driver/vm_mock.go
docs/builders/vsphere-iso.mdx

1. st commit improves code coverage by factoring out a function to list cdrom devices. Although, there's very little change in the test from that, bug I guess it's good to have a better testing.
2. nd commit is the fix. As described in the commit, previously we used `ISOPaths` to figure out amount of cdroms, but that's not really correct and this assumption breaks when `remove_cdrom` is set. Fix the problem by making use of the function listing the devices that was added in prev. commit.
3. rd commit is just a fix to the tests that nils out the list of ISOPaths added in `EjectCdrom`, which seems to be correct because after it's called we should no longer have paths mounted, only the actual cdrom hw devices. With that said, it seems this does not have any influence on the tests right now. …

fix: use cdroms len instead of ISOPaths len

---

.web-docs/components/post-processor/vsphere/README.md
docs-partials/post-processor/vsphere/Config-not-required.mdx
post-processor/vsphere/post-processor.go
post-processor/vsphere/post-processor.hcl2spec.go

- Updates the `vsphere` post-processor to support `max_retries` for the upload to a vSphere endpoint. Defaults to 5.
- Sets and uses constants for `DefaultMaxRetries`, `DefaultDiskMode`, and `OvftoolWindows`.
Closes #30

feat: upload max retries

---

builder/vsphere/common/output_config.go

If running on Windows, do not attempt to apply Unix-style permissions to the artifact output.
Closes #280

fix: skip unix-style permissions

---

builder/vsphere/common/step_wait_for_ip.go

**Summary**
To use a literal IPv6 address in a URL, the literal address must be enclosed in "`[`" and "`]`" characters.
```
ssh example@[2010:836B:4179::836B:4179]
```
Refer to https://www.ietf.org/rfc/rfc2732.
Closes: #333

fix: ipv6 rfc2732

---

.web-docs/components/builder/vsphere-clone/README.md
docs/builders/vsphere-clone.mdx

- Cleaned up Windows and Linux customization options on `vsphere-clone` documentation.
- Fixed broken links for Linux and Windows options.
- Added missing Windows options and examples.
```sh
─░▒▓    ~/git/personal/packer-plugin-vsphere  on   docs/windows_options ▓▒░·····························································································░▒▓ ✔  at 12:04:04  ▓▒░─╮
╰─ make generate                                                                                                                                                                                        ─╯
2024/04/03 12:04:21 Copying "docs" to ".docs/"
2024/04/03 12:04:21 Replacing @include '...' calls in .docs/
╭─ …
```

docs: fix links and options

---

builder/vsphere/driver/vm_test.go
go.mod
go.sum

- Updates `vmware/govmom` from 0.36.2 to 0.37.1.
- Due to a change in 0.37.0 of `vmware/govmom`, the `ReconfigureFail` needed to be removed. The CreateTask method in the TaskManager struct was updated. The new method now checks if the provided TaskTypeId is valid before proceeding. If it's not valid, it returns a SOAP fault with an InvalidArgument error.
```console
➜  packer-plugin-vsphere git:(chore(deps)-govmomi) ✗ go get -u github.com/vmware/govmomi                                          
go: upgraded github.com/vmware/govmomi v0.36.2 => v0.37.1
➜  packer-plugin-vsphere git:(chore(deps)-govmomi) ✗ go mod tidy
➜  packer-plugin-vsphere git:(chore(deps)-govmomi) ✗ make generate
2024/05/01 13:44:33 Copying "docs" to ".docs/"
2024/05/01 13:44:33 Replacing @include '...' calls in .docs/ …
```

chore(deps): bump github.com/vmware/govmomi from 0.36.2 to 0.37.1

---

.web-docs/components/builder/vsphere-clone/README.md
builder/vsphere/clone/step_clone.go
builder/vsphere/driver/disk.go
builder/vsphere/driver/vm.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx

- Clarifies that `disk_size` in the `vsphere-clone` builder only supports a single disk.
- Adds a `TODO` note for future enhancements to `findDisk` and `ResizeDisk` functions.
###Tessting
```sh
packer-plugin-vsphere1 on  docs/disk-size-usage via 🐹 v1.22.2 
2024/04/18 21:14:24 Copying "docs" to ".docs/"
2024/04/18 21:14:24 Replacing @include '...' calls in .docs/
packer-plugin-vsphere1 on  docs/disk-size-usage via 🐹 v1.22.2 took 12.5s 
➜ make build   
packer-plugin-vsphere1 on  docs/disk-size-usage via 🐹 v1.22.2 took 5.2s 
➜ make test
? …
```

docs: `disk_size`

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/config.hcl2spec.go
builder/vsphere/common/step_hardware.go
builder/vsphere/common/step_hardware.hcl2spec.go
builder/vsphere/common/step_hardware_test.go
builder/vsphere/driver/vm.go
builder/vsphere/iso/config.hcl2spec.go
docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
docs-partials/builder/vsphere/common/PCIPassthroughAllowedDevice-not-required.mdx
docs-partials/builder/vsphere/common/PCIPassthroughAllowedDevice.mdx
docs/builders/vsphere-iso.mdx

As a part of the Assignable Hardware framework in vSphere 7, Dynamic DirectPath I/O is introduced. When configuring a virtual machine to use a PCIe device using Dynamic Direct I/O path, enables the Assignable Hardware intelligence for passthrough devices. No longer is the hardware address of the PCIe device directly mapped to the virtual machine configuration file (the .vmx file). Instead, the attributes, or capabilities, are exposed to the virtual machine.
```hcl
source "vsphere-iso" "example" {
vcenter_server       = var.vsphere_server
username             = var.vsphere_username
password             = var.vsphere_password
datacenter           = var.vsphere_datacenter
cluster              = var.vsphere_cluster
datastore            = var.vsphere_datastore
network              = …
```

feat: add support for dynamic directpath i/o

---

post-processor/vsphere/post-processor.go

- Adds the option to allow ovftool to use `--noSSLVerify` if insecure is set to `false`.
- Adds an error, similar to incorrect credentials error, message if the ovftool's target endpoint's SSL thumbprint is not trusted by the Packer host and suggests remediation options.
- Updates error, log, ui, and fatal messages.
**Build**
```console
packer-plugin-vsphere1 on  fix/ovftool-error-handling- [?] via 🐹 v1.22.2 
2024/04/25 09:52:13 Copying "docs" to ".docs/"
2024/04/25 09:52:13 Replacing @include '...' calls in .docs/
packer-plugin-vsphere1 on  fix/ovftool-error-handling- [?] via 🐹 v1.22.2 took 13.5s 
➜ make build
packer-plugin-vsphere1 on  fix/ovftool-error-handling- [?] via 🐹 v1.22.2 took 5.0s 
➜ make test
? …
```

fix: ovftool error handling

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/step_clone.go
builder/vsphere/driver/network.go
builder/vsphere/driver/vm.go
builder/vsphere/iso/step_create.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
docs-partials/builder/vsphere/iso/NIC-not-required.mdx

- Updates the error messages when more than one network with the same name resolves to more than one network.
- Updated the documentation for `network` in `vsphere-iso` and `vsphere-clone` builders.
```console
➜  packer-plugin-vsphere git:(fix/multiple-network-error-msg) ✗ go fmt builder/vsphere/driver/vm.go
➜  packer-plugin-vsphere git:(fix/multiple-network-error-msg) ✗ go fmt builder/vsphere/driver/network.go 
➜  packer-plugin-vsphere git:(fix/multiple-network-error-msg) ✗ go fmt builder/vsphere/iso/step_create.go
➜  packer-plugin-vsphere git:(fix/multiple-network-error-msg) ✗ go fmt builder/vsphere/clone/step_clone.go
➜  packer-plugin-vsphere git:(fix/multiple-network-error-msg) ✗ make generate
2024/04/25 22:52:24 Copying "docs" to ".docs/"
2024/04/25 22:52:24 Replacing @include '...' …
```

fix: multiple network error msg

---

.web-docs/components/post-processor/vsphere-template/README.md
docs-partials/post-processor/vsphere-template/Config-not-required.mdx
post-processor/vsphere-template/post-processor.go
post-processor/vsphere-template/post-processor.hcl2spec.go
post-processor/vsphere-template/step_mark_as_template.go

Adds the ability to set the name of the of the template in the `vsphere-template` post-processor. If `template_name` is not provided, the name of the source virtual machine will be used.
**General**: PASS ✅ 
```console
packer-plugin-vsphere1 on  feat/set-template-name [$!] via 🐹 v1.22.2 
2024/04/27 21:02:44 Copying "docs" to ".docs/"
2024/04/27 21:02:44 Replacing @include '...' calls in .docs/
packer-plugin-vsphere1 on  feat/set-template-name [$!] via 🐹 v1.22.2 took 11.6s 
➜ make build
packer-plugin-vsphere1 on  feat/set-template-name [$!] via 🐹 v1.22.2 took 3.5s 
➜ make test
? …
```

feat: set template name

---

.web-docs/README.md
README.md
docs/README.md

Updates the format and content, as well as add information on the difference between this plugin and `packer-plugin-vmware`.
- `./README.md`
- `./docs/README.md`
Ref: https://github.com/hashicorp/packer-plugin-vmware/issues/145

docs: update `README.md`

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/builder.go
builder/vsphere/common/step_export.go
builder/vsphere/common/step_export.hcl2spec.go
builder/vsphere/common/step_import_to_content_library.go
builder/vsphere/iso/builder.go
docs-partials/builder/vsphere/common/ContentLibraryDestinationConfig-not-required.mdx
docs-partials/builder/vsphere/common/ExportConfig-not-required.mdx

Adds support to export a virtual machine image to either to the default Open Virtualization Format (`ovf`) or convert to Open Virtualization Archive (.ova).
> [!NOTE]
> To use the `ova` format option, VMware ovftool must be installed on the Packer host and accessible in either the system `PATH` or the user's `PATH`. This is noted in the documentation.
Standard Build and Tests:
```sh
➜  packer-plugin-vsphere git:(feat/export-to-ova) ✗ make generate
2024/04/18 15:30:19 Copying "docs" to ".docs/"
2024/04/18 15:30:19 Replacing @include '...' calls in .docs/
➜  packer-plugin-vsphere git:(feat/export-to-ova) make build
➜  packer-plugin-vsphere git:(feat/export-to-ova) make test
?       github.com/hashicorp/packer-plugin-vsphere …
```

feat: add support for export to ova

---

.web-docs/components/builder/vsphere-clone/README.md
builder/vsphere/clone/step_customize.go
docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx

Updates `RunOnceCommandList` to a slice of strings `[]string` and updates `guiRunOnce()` to pass `""` if no commands are provided. This will ensure that the function addresses each case.
Basic:
```console
➜  packer-plugin-vsphere git:(fix/run-once-command-list) make generate             
2024/05/09 22:24:23 Copying "docs" to ".docs/"
2024/05/09 22:24:23 Replacing @include '...' calls in .docs/
➜  packer-plugin-vsphere git:(fix/run-once-command-list) make build
➜  packer-plugin-vsphere git:(fix/run-once-command-list) make test
? …
```

fix: run once command list

---

.web-docs/components/builder/vsphere-clone/README.md
builder/vsphere/clone/config.go
builder/vsphere/clone/step_clone.go
builder/vsphere/clone/step_customize.go
docs-partials/builder/vsphere/clone/CloneConfig-not-required.mdx
docs-partials/builder/vsphere/clone/Config-not-required.mdx
docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx
docs-partials/builder/vsphere/clone/CustomizeConfig.mdx
docs-partials/builder/vsphere/clone/GlobalDnsSettings-not-required.mdx
docs-partials/builder/vsphere/clone/GlobalDnsSettings.mdx
docs-partials/builder/vsphere/clone/GlobalRoutingSettings-not-required.mdx
docs-partials/builder/vsphere/clone/GlobalRoutingSettings.mdx
docs-partials/builder/vsphere/clone/LinuxOptions-not-required.mdx
docs-partials/builder/vsphere/clone/NetworkInterface-not-required.mdx
docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
docs-partials/builder/vsphere/clone/vAppConfig-not-required.mdx

Update the docs for the `step_clone` and `step_customize` to be a little less jarring and add uniform comment formatting.

docs: update `vsphere-clone`

---

.web-docs/README.md
.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
.web-docs/components/post-processor/vsphere/README.md
README.md
builder/vsphere/common/step_config_params.go
builder/vsphere/common/step_hardware.go
builder/vsphere/iso/step_create.go
docs-partials/builder/vsphere/common/ConfigParamsConfig-not-required.mdx
docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
docs-partials/builder/vsphere/iso/CreateConfig-not-required.mdx
docs-partials/post-processor/vsphere/Config-not-required.mdx
docs/README.md
post-processor/vsphere/post-processor.go

Updates links to broadcom.com sites, as needed.
- KB Articles
- Product Lifecycle
- Developer Portal

docs: update links

---

builder/vsphere/common/step_connect.go

When attempting to cleanup the existing connections to the VSphere cluster, we get the driver from the state shared between all steps in order to run the commands necessary for that.
This can however fail, if the step couldn't succeed for any reason.
Then, if the connection fails and the driver isn't set in the state, when running Cleanup on the connect step, we get the driver from state and cast it to a driver.Driver.
This will make the plugin crash, and so we change how we proceed here, by getting the driver with a `GetOk`, exiting if it failed to be fetched from state, then casting the result if it was created in state.
This should prevent crashes like those.
Closes: #436

fix: don't assume driver isn't nil in StepConnect

---

.github/ISSUE_TEMPLATE/config.yml

Adds the `config.yml` for issues to show contact links to the following alongside the options for bugs, enhancements, questions, etc.
The result is that it will look similar to what is used for `hashicorp/terraform-provider-vsphere`.
Example:

chore: add issues `config.yml`

---

.golangci.yml

Removes the use of the following linters: `deadcode` and `varcheck`.
Both are deprecated as of `golangci-lint` v1.49.0. The owners seem to have abandoned these linters and they are replaced by `unused`.
Also corrected deprecated configuration options: `run.skip-files`, `output.format`, and `linters.errcheck.ignore`.
**Before**:
```sh
packer-plugin-vsphere on chore/update-golangci
➜ golangci-lint run
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`. 
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats` 
WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`. 
WARN The linter 'deadcode' is …
```

chore: update `golangci.yml`

---

builder/vsphere/clone/step_customize.go
builder/vsphere/common/step_add_cdrom.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_mock.go
post-processor/vsphere/post-processor.go
post-processor/vsphere/post-processor_test.go

Updates variable names that do not use mixed caps to be more idiomatic Go code.
In Go, the convention is to use `MixedCaps` or `mixedCaps` rather than underscores to write multi-word names. This applies to both exported and unexported identifiers, such as constants, variables, types, fields, functions, etc.
This is not a functional change, but it makes your code more consistent with the style that Go developers expect.
```sh
packer-plugin-vsphere on fix/use-mixed-caps
2024/06/18 22:39:03 Copying "docs" to ".docs/"
2024/06/18 22:39:03 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on fix/use-mixed-caps
➜ make build
packer-plugin-vsphere on fix/use-mixed-caps
➜ make test
? …
```

 fix: use mixed caps

---

post-processor/vsphere-template/step_choose_datacenter.go
post-processor/vsphere-template/step_create_folder.go
post-processor/vsphere-template/step_create_snapshot.go
post-processor/vsphere-template/step_mark_as_template.go

Refactors instances of `ui.Error(err.Error())` to use `ui.Errorf("%s", err)` in the post processors, as introduced in v0.5.3 of the `packer-plugin-sdk`.

refactor: post-processor ui errors

---

builder/vsphere/driver/library.go
builder/vsphere/driver/vm.go

Simplifies `err.Error()` to just `err`.

chore: update use of `err.Error()`

---

examples/builder/vsphere-supervisor/jenkins-template.pkr.hcl

This PR updates the Supervisor builder example template to install a newer JDK version.
The current JDK version (11) is no longer supported by the latest Jenkins release (2.426.1):
```console
packer@jenkins-test:~$ jenkins
Running with Java 11 from /usr/lib/jvm/java-11-openjdk-amd64, which is older than the minimum required version (Java 17).
Supported Java versions are: [17, 21]
```
The Packer command ran successfully using the updated template file:
```console
$ packer build jenkins-template.pkr.hcl
vsphere-supervisor.vm: output will be in this color.
==> vsphere-supervisor.vm: Creating temporary RSA SSH key for instance...
vsphere-supervisor.vm: Connecting to Supervisor cluster...
...
vsphere-supervisor.vm: Source VM is now ready in Supervisor cluster
...
==> vsphere-supervisor.vm: …
```

chore: update supervisor plugin example jenkins template

---

go.mod
go.sum

Updates `github.com/hashicorp/go-retryablehttp` from v0.7.6 => v0.7.7.
```console
packer-plugin-vsphere on  chore(deps)/go-retryablehttp [$] via 🐹 v1.22.4 
✦ ➜ go get -u github.com/hashicorp/go-retryablehttp  
go: upgraded github.com/hashicorp/go-retryablehttp v0.7.6 => v0.7.7
packer-plugin-vsphere on  chore(deps)/go-retryablehttp [$!] via 🐹 v1.22.4 
✦ ➜ go mod tidy
packer-plugin-vsphere on  chore(deps)/go-retryablehttp [$!] via 🐹 v1.22.4 
✦ ➜ go fmt ./...
packer-plugin-vsphere on  chore(deps)/go-retryablehttp [$!] via 🐹 v1.22.4 
✦ ➜ make build
packer-plugin-vsphere on  chore(deps)/go-retryablehttp [$!] via 🐹 v1.22.4 took 4.3s 
✦ ➜ make generate
2024/06/27 16:41:44 Copying "docs" to ".docs/"
2024/06/27 16:41:44 Replacing @include '...' calls in .docs/
Compiling MDX docs in '.docs' to …
```

chore(deps): hashicorp/go-retryablehttp

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/clone/builder.go
builder/vsphere/common/http_address.go
builder/vsphere/common/step_boot_command.go
builder/vsphere/common/step_http_ip_discover.go
builder/vsphere/iso/builder.go
docs-partials/builder/vsphere/common/BootConfig-not-required.mdx
docs/builders/vsphere-clone.mdx
docs/builders/vsphere-iso.mdx

Adds support for `http_interface` and `http_bind_interface` from the SDK.
> [!NOTE] 
> - The options `http_bind_address` and `http_interface` are mutually exclusive, per the SDK.
> - Both `http_bind_address` and `http_interface` have higher priority than `http_ip`.
> - The `http_bind_address` is matched against the IP addresses of the host's network interfaces. If no match is found, the plugin will terminate.
> - Similarly, `http_interface` is compared with the host's network interfaces. If there's no corresponding network interface, the plugin will also terminate.
> - If neither `http_bind_address`, `http_interface`, and `http_ip` are provided, the plugin will automatically find and use the IP address of the first non-loopback interface for `http_ip`.
> - If `http_ip` is provided and the …

feat: add support for `http_interface` and `http_bind_address`

---

post-processor/vsphere/post-processor.go

Removes the joined commands which would contain credentials, if logged.
```console
packer-plugin-vsphere on  fix/remove-ovftool-commands-from-logs via 🐹 v1.23.0 
➜ go fmt ./...
packer-plugin-vsphere on  fix/remove-ovftool-commands-from-logs via 🐹 v1.23.0 
➜ make test   
?       github.com/hashicorp/packer-plugin-vsphere/examples/driver      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/version      [no test files]
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        2.606s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common       4.567s
ok …
```

fix: remove ovftool commands from logs

---

builder/vsphere/driver/vm.go

Fixes incorrect conversion of an unsigned 32-bit integer from  to a lower bit size type int32 without an upper bound check.
```console
packer-plugin-vsphere on  fix/incorrect-conversion via 🐹 v1.23.0 
➜ go fmt ./...
packer-plugin-vsphere on  fix/incorrect-conversion via 🐹 v1.23.0 
➜ make test   
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/testing [no test files]
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        2.267s
?       github.com/hashicorp/packer-plugin-vsphere/examples/driver      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/version      [no test files]
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common …
```

fix: incorrect conversion between integer types

---

.web-docs/components/builder/vsphere-supervisor/README.md
builder/vsphere/supervisor/step_create_source.go
docs-partials/builder/vsphere/supervisor/CreateSourceConfig-not-required.mdx

- Updates `DefaultSourceNamePrefix` to "source".
- Limits the name of the source virtual machine to 15 characters to support Windows. This was causing issues for deploying Windows VMs as they require a shorter hostname.
Closes #455

fix: limit source vm to 15 char

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
builder/vsphere/common/step_config_params.go
builder/vsphere/driver/vm.go
docs-partials/builder/vsphere/common/ConfigParamsConfig-not-required.mdx

Updates to the documentation, improvements to logging, and enhancements to error handling in the `vsphere` builder components. The most important changes include adding examples to the documentation, improving logging for configuration parameters, and enhancing error handling during VM reconfiguration.
Documentation Updates:
* [`.web-docs/components/builder/vsphere-clone/README.md`](diffhunk://#diff-259290b43a88f7ba6c250e0f0cd285a8c6b0c063643e34aa78de285d3ef29445L294-R326): Added HCL and JSON examples for `configuration_parameters` and notes on ignored keys.
* [`.web-docs/components/builder/vsphere-iso/README.md`](diffhunk://#diff-6752170ad5617582d4773e4abc3c9a943a0685112b0b5591bd80239ee6aa08deL1399-R1431): Added HCL and JSON examples for `configuration_parameters` and notes on ignored …

fix: configuration parameters

---

builder/vsphere/common/http_address.go

Updates `ValidateHTTPAddress` to simply log a warning if the `http_ip` is not bound to an interface instead of error.
Closes #474

fix: `http_ip` warn vs err

---

builder/vsphere/clone/step_customize.go

This pull request includes a small change to the `builder/vsphere/clone/step_customize.go` file that removes the nil check for `w.RunOnceCommandList` since `len()` for a `nil` slice is defined as zero. The change simplifies the conditional check
```shell
packer-plugin-vsphere on fix/remove-nil-check  via 🐹 v1.23.2 
➜ staticcheck builder/vsphere/clone/step_customize.go 
builder/vsphere/clone/step_customize.go:443:5: should omit nil check; len() for []string is defined as zero (S1009)
```
```shell
packer-plugin-vsphere on fix/remove-nil-check  via 🐹 v1.23.2 
➜ staticcheck builder/vsphere/clone/step_customize.go
packer-plugin-vsphere on fix/remove-nil-check  [!] via 🐹 v1.23.2 
➜       
```

fix: remove nil check

---

builder/vsphere/supervisor/step_import_image.go

Simplifies the condition for checking if the image import request was created.
```shell
➜ staticcheck builder/vsphere/supervisor/step_import_image.go                                             
builder/vsphere/supervisor/step_import_image.go:166:69: should omit comparison to bool constant, can be simplified to !v.(bool) (S1002)
```
```shell
➜ staticcheck builder/vsphere/supervisor/step_import_image.go                                             
➜
```

fix: omit comparison to bool constant

---

builder/vsphere/supervisor/step_create_source.go
builder/vsphere/supervisor/step_import_image.go

This PR resolves supervisor-builder lint issues reported from the current golangci-lint-action version.

chore: resolve supervisor-builder lint issue

---

builder/vsphere/clone/step_clone.go
builder/vsphere/clone/step_clone_test.go

This PR addresses an issue in the `vsphere-clone` builder where using the `-force` flag can lead to unintentional deletion of the target VM, which may result in the loss of critical data if the target VM is the only copy of a virtual machine. 
Currently, when the `-force` flag is specified, the `vsphere-clone` builder first deletes the target VM before verifying that the source VM to be cloned exists. If the source VM is missing, this process leaves users without a VM to clone and potentially results in data loss.
In our environment, Packer is used to perform regular updates on legacy virtual machine templates. These templates are unique, lack proper build configurations, and cannot be easily replicated. If, for any reason, human intervention results in running `packer build` with the …

fix: `vsphere-clone`: rearrange build steps to ensure source VM exists before deleting target

---

.web-docs/components/builder/vsphere-clone/README.md
.web-docs/components/builder/vsphere-iso/README.md
.web-docs/components/builder/vsphere-supervisor/README.md
README.md
builder/vsphere/clone/step_customize.go
builder/vsphere/common/step_hardware.go
builder/vsphere/common/storage_config.go
docs-partials/builder/vsphere/clone/CustomizeConfig.mdx
docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
docs-partials/builder/vsphere/common/StorageConfig-not-required.mdx
docs/builders/vsphere-iso.mdx
docs/builders/vsphere-supervisor.mdx

Updates product documentation links to new `techdocs.broadcom.com` locations, as needed.
Closes #502

chore(docs): update links

---

builder/vsphere/driver/cluster.go
builder/vsphere/driver/datastore.go
builder/vsphere/driver/disk.go
builder/vsphere/driver/driver.go
builder/vsphere/driver/folder.go
builder/vsphere/driver/host.go
builder/vsphere/driver/library.go
builder/vsphere/driver/network.go
builder/vsphere/driver/resource_pool.go
builder/vsphere/driver/vm.go
builder/vsphere/driver/vm_cdrom.go
builder/vsphere/driver/vm_keyboard.go

Adds or updates the Go Doc comments for the driver functions.
```shell
packer-plugin-vsphere on  chore/driver-godoc [!] via 🐹 v1.23.5 
➜ go fmt ./...
packer-plugin-vsphere on  chore/driver-godoc [!] via 🐹 v1.23.5 took 33.2s 
2025/01/26 14:22:21 Copying "docs" to ".docs/"
2025/01/26 14:22:21 Replacing @include '...' calls in .docs/
packer-plugin-vsphere on  chore/driver-godoc [!] via 🐹 v1.23.5 
➜ make test
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/utils[no test files]
? …
```

chore: driver godoc

---

builder/vsphere/clone/step_customize_test.go

Removes redundant type.
```shell
~/Downloads/packer-plugin-vsphere git:[refactor/remove-redundant-type]
go fmt ./...
~/Downloads/packer-plugin-vsphere git:[refactor/remove-redundant-type]
make build
~/Downloads/packer-plugin-vsphere git:[refactor/remove-redundant-type]
make test
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        1.770s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common       3.931s
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/utils [no test files]
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver …
```

refactor: remove redundant type

---

builder/vsphere/driver/vm.go

Replaces empty slice declaration with nil slice declaration.
An empty slice can be represented by nil or an empty slice literal. They are functionally equivalent — their len and cap are both zero — but the nil slice is the preferred style. 
```shell
~/Downloads/packer-plugin-vsphere git:[refactor/use-nil-slice-declaration]
go fmt ./...
~/Downloads/packer-plugin-vsphere git:[refactor/use-nil-slice-declaration]
make build
~/Downloads/packer-plugin-vsphere git:[refactor/use-nil-slice-declaration]
make test
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        1.772s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common       3.930s
? …
```

refactor: use nil slice declaration

---

post-processor/vsphere/post-processor.go

Removed variable type declaration inferred by the compiler.
```shell
~/Downloads/packer-plugin-vsphere git:[refactor/omit-type-declaration]
go fmt ./...
~/Downloads/packer-plugin-vsphere git:[refactor/omit-type-declaration]
make build
~/Downloads/packer-plugin-vsphere git:[refactor/omit-type-declaration]
make test
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        1.721s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common       3.885s
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/utils [no test files]
ok …
```

refactor: omit type declaration

---

post-processor/vsphere-template/step_create_snapshot.go
post-processor/vsphere-template/step_mark_as_template.go

TL;DR: Export the return type for exported functions.
Refactors the naming conventions for struct types and their associated methods in the `post-processor/vsphere-template` package to improve consistency and align with Go naming standards. The changes involve renaming private struct types to exported ones and updating all related method signatures accordingly.
* The `stepCreateSnapshot` struct has been renamed to `StepCreateSnapshot`, making it an exported type. All associated methods (`NewStepCreateSnapshot`, `Run`, and `Cleanup`) have been updated to reflect this change. [[1]](diffhunk://#diff-96ba201a7b3dc867f393bfeb954034b5e257131b0d2b737e5a741d96dd877219L16-R24) [[2]](diffhunk://#diff-96ba201a7b3dc867f393bfeb954034b5e257131b0d2b737e5a741d96dd877219L35-R35) …

refactor: exported functions with unexported return types

---

builder/vsphere/driver/datastore.go
builder/vsphere/driver/folder.go
builder/vsphere/driver/resource_pool.go
builder/vsphere/driver/vm.go

Replaces type assertion on errors with a call to `errors.As`.
The preferred way for checking for a specific error type is to use the `errors.As` function from the standard library as this function traverses the chain of the wrapped errors while checking for a specific error type.
```shell
~/Downloads/packer-plugin-vsphere git:[refactor/replaces-type-assertion]
go fmt ./...
~/Downloads/packer-plugin-vsphere git:[refactor/replaces-type-assertion]
make build
~/Downloads/packer-plugin-vsphere git:[refactor/replaces-type-assertion]
make test
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        1.702s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common       3.275s
? …
```

refactor: replace type assertion on errors

---

.github/workflows/go-validate.yml

Bumps golangci-lint to v1.60.1.

chore(gh): bump golangci-lint to v1.60.1

---

.github/workflows/go-validate.yml
.golangci.yml
builder/vsphere/clone/builder.go
builder/vsphere/clone/config_test.go
builder/vsphere/driver/datastore.go
builder/vsphere/iso/builder.go
builder/vsphere/supervisor/builder.go

Updates `golangci-lint` to v2 (`latest`).
- Migrated the configuration.
- Updates the `golangci/golangci-lint-action` to v7 for interoperability.
- Addresses existing linting issues.
```shell
~/Downloads/packer-plugin-vsphere git:[main]
golangci-lint migrate
WARN The configuration comments are not migrated. 
WARN Details about the migration: https://golangci-lint.run/product/migration-guide/ 
╭───────────────────────────────────────────────────────────────────────────╮
│                                                                           │
│                               We need you!                                │
│                                                                           │
│ Donations help fund the ongoing development and maintenance of this tool. │
│  If …
```

chore: update golangci-lint to v2

---

builder/vsphere/driver/datastore.go

Fix the type assertion on errors to use the `*object.DatastoreNoSuchDirectoryError` pointer.
Follow-up to #530.
```shell
~/Downloads/packer-plugin-vsphere git:[fix/type-assertion-on-errors]
go fmt ./...
~/Downloads/packer-plugin-vsphere git:[fix/type-assertion-on-errors]
go fmt ./...
~/Downloads/packer-plugin-vsphere git:[fix/type-assertion-on-errors]
make dev
packer plugins install --path packer-plugin-vsphere "github.com/hashicorp/vsphere"
Successfully installed plugin github.com/hashicorp/vsphere from /Users/johnsonryan/Downloads/packer-plugin-vsphere/packer-plugin-vsphere to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vsphere/packer-plugin-vsphere_v1.4.3-dev_x5.0_darwin_amd64
~/Downloads/packer-plugin-vsphere git:[fix/type-assertion-on-errors]
make build …
```

fix: type assertion on errors

---

version/version.go

Updates to v2.0.0-dev.
Ref: #501
```shell
packer-plugin-vsphere on  chore/prepare-v2.0.0-dev via 🐹 v1.23.8 
➜ make build
packer-plugin-vsphere on  chore/prepare-v2.0.0-dev via 🐹 v1.23.8 took 27.5s 
➜ make dev
packer plugins install --path packer-plugin-vsphere "github.com/hashicorp/vsphere"
Successfully installed plugin github.com/hashicorp/vsphere from /Users/johnsonryan/Downloads/packer-plugin-vsphere/packer-plugin-vsphere to /Users/johnsonryan/.packer.d/plugins/github.com/hashicorp/vsphere/packer-plugin-vsphere_v2.0.0-dev_x5.0_darwin_amd64
```

chore: bump to v2.0.0-dev
