builder/vsphere/driver/vm.go, builder/vsphere/driver/vm_test.go
=> Add address type when updating macaddress at clone

docs/builders/vsphere-clone.mdx, docs/builders/vsphere-iso.mdx
fix https://github.com/hashicorp/packer/issues/11085
=> Docs: Fix examples folder location link

docs/builders/vsphere-iso.mdx
In order to have a good experience with our community, we recommend that you
read the contributing guidelines for making a PR, and understand the lifecycle
of a Packer Plugin PR:
https://github.com/hashicorp/packer-plugin-vsphere/blob/main/.github/CONTRIBUTING.md#opening-an-pull-request
- Correct the term from permissions to privileges.
- Add a table with the context of privileges based on plugin capabilities.
- Add context for global permissions and the content library.
Based on contributor's content at [vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere).
If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:
Closes #57
=> Update vSphere privileges in `vsphere-iso.mdx`

builder/vsphere/clone/config.hcl2spec.go, builder/vsphere/common/step_hardware.go, builder/vsphere/common/step_hardware.hcl2spec.go, builder/vsphere/common/step_hardware_test.go, builder/vsphere/driver/vm.go, builder/vsphere/driver/vm_test.go, builder/vsphere/iso/config.hcl2spec.go, docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
=> Support adding vTPM device

post-processor/vsphere-template/step_mark_as_template.go
=> Fix regex escape in template post-processor

builder/vsphere/clone/step_customize.go, builder/vsphere/clone/step_customize.hcl2spec.go, docs-partials/builder/vsphere/clone/CustomizeConfig-not-required.mdx, docs-partials/builder/vsphere/clone/WindowsOptions-not-required.mdx
Ported from terraform vsphere virtual machine resource
Closes #177
=> feat: Add customization for Windows guest OS

builder/vsphere/common/step_connect.go
=> fix: add type check in step_connect cleanup

.web-docs/metadata.hcl
=> Update metadata.hcl to include HCP flag

.web-docs/components/builder/vsphere-iso/README.md, docs/builders/vsphere-iso.mdx
Correction to the Required vSphere Privileges to correct reference for Datastore -> Low Level File Operations
=> docs: update privilege reference

.web-docs/components/post-processor/vsphere/README.md, docs/post-processors/vsphere.mdx
Update `hardware_version` content in `vsphere-clone` post-processor docs.
Closes: #260
=> docs: `hardware_version` in `vsphere-clone`

.web-docs/components/builder/vsphere-clone/README.md, .web-docs/components/builder/vsphere-iso/README.md, builder/vsphere/common/config_location.go, docs-partials/builder/vsphere/common/LocationConfig-not-required.mdx
- Updates the documentation for location items.
- Updates the `resource_pool` to note the need for a full path to a nested resource pool.
Ref #304
=> docs: update location content

version/version.go
- version: cut release 1.2.4
- version: prepare for 1.2.5 dev
=> Cut release 1.2.4

README.md, version/version.go
- Cut release 1.2.5
- Prepare for 1.2.6 development
=> Update version for v1.2.5 release

.web-docs/components/builder/vsphere-iso/README.md, .web-docs/components/builder/vsphere-supervisor/README.md, docs/builders/vsphere-iso.mdx, docs/builders/vsphere-supervisor.mdx
Summary
Updates external documentation links to vSphere 8.0.
=> docs: update external documentation links

.web-docs/components/builder/vsphere-clone/README.md, .web-docs/components/builder/vsphere-iso/README.md, builder/vsphere/common/storage_config.go, docs-partials/builder/vsphere/common/DiskConfig.mdx
=> docs: fix markup

.web-docs/components/builder/vsphere-clone/README.md, .web-docs/components/builder/vsphere-iso/README.md, builder/vsphere/clone/step_customize.go, builder/vsphere/common/output_config.go, builder/vsphere/common/step_add_cdrom.go, builder/vsphere/common/step_export.go, builder/vsphere/common/step_import_to_content_library.go, builder/vsphere/common/step_shutdown.go, builder/vsphere/common/step_wait_for_ip.go, builder/vsphere/driver/vm.go, builder/vsphere/driver/vm_cdrom.go, builder/vsphere/driver/vm_cdrom_test.go, builder/vsphere/iso/step_create.go, builder/vsphere/supervisor/config.go, builder/vsphere/supervisor/step_publish_source.go, docs-partials/builder/vsphere/clone/NetworkInterface-not-required.mdx, docs-partials/builder/vsphere/common/ContentLibraryDestinationConfig-not-required.mdx, docs-partials/builder/vsphere/common/ContentLibraryDestinationConfig.mdx, docs-partials/builder/vsphere/common/ExportConfig-not-required.mdx, docs-partials/builder/vsphere/common/OutputConfig-not-required.mdx, docs-partials/builder/vsphere/common/ShutdownConfig-not-required.mdx, docs-partials/builder/vsphere/common/WaitIpConfig-not-required.mdx
Updates grammar in comments and documentation, as needed.
=> chore: update grammar

post-processor/vsphere-template/post-processor_test.go
Removes redundant parentheses.
=> fix: redundant parentheses

main.go
Replaces use of `snake_case` with `camelCase`.
=> fix: remove use of snake case

builder/vsphere/common/step_add_cdrom.go
- Utilize `errors.Is` for accurate error comparison when checking for `ErrNoSataController`, allowing for correct handling of wrapped errors.
- Implement error wrapping with `%w` in `fmt.Errorf` to preserve underlying error information.
- Add handling for unexpected error conditions from `FindSATAController` to ensure robustness.
=> fix: improve sata controller error handling

builder/vsphere/iso/builder.go, builder/vsphere/iso/builder_acc_test.go, builder/vsphere/iso/common_test.go, builder/vsphere/iso/config.go, builder/vsphere/iso/step_create.go, builder/vsphere/iso/step_create_test.go
Adds or updates the Go Doc comments for the `common/iso` functions.
=> chore: common iso godoc

README.md, version/version.go
=> version: cut release v2.0.0
